import { Rubric, RubricTemplate } from './types';

export const sampleRubrics: Rubric[] = [
  {
    id: 'rb-1',
    name: 'Design of Algorithms (Project 1)',
    subjectCode: 'COMP20007',
    rowCount: 12,
    version: 3,
    templateId: 'tpl-100',
    templateVersion: 4, // template newer than instance → update available
    updatedAt: '2025-09-18T11:12:00.000Z',
    status: 'update-available',
    ownerId: 'me',
    shared: false,
  },
  {
    id: 'rb-2',
    name: 'Software Modelling & Design (Group Project)',
    subjectCode: 'SWEN30006',
    rowCount: 8,
    version: 1,
    templateId: null,
    templateVersion: undefined,
    updatedAt: '2025-09-10T08:45:00.000Z',
    status: 'active',
    ownerId: 'me',
    shared: true,
  },
  {
    id: 'rb-3',
    name: 'Computer Systems (Project 2)',
    subjectCode: 'COMP30023',
    rowCount: 10,
    version: 2,
    templateId: 'tpl-200',
    templateVersion: 2,
    updatedAt: '2025-08-29T16:24:00.000Z',
    status: 'active',
    ownerId: 'me',
    shared: false,
  },
  {
    id: 'rb-4',
    name: 'Computer Systems (Project 1)',
    subjectCode: 'COMP30023',
    rowCount: 10,
    version: 1,
    templateId: 'tpl-200',
    templateVersion: 2,
    updatedAt: '2025-08-01T16:24:00.000Z',
    status: 'active',
    ownerId: 'me',
    shared: false,
  },
  {
    id: 'rb-5',
    name: 'Information Security & Privacy (Written Assignment)',
    subjectCode: 'INFO30026',
    rowCount: 5,
    version: 5,
    templateId: null,
    templateVersion: undefined,
    updatedAt: '2025-05-01T16:24:00.000Z',
    status: 'active',
    ownerId: 'me',
    shared: false,
  },
];

export const sampleTemplates: RubricTemplate[] = [
  {
    id: 'tpl-100',
    name: 'Design of Algorithms (Coding Assignment Template)',
    version: 4,
    subjectCode: 'COMP20007',
    rowCount: 10,
    description:'',
    updatedAt: '2025-09-12T10:22:00.000Z',
    createdBy: 'admin',
  },
  {
    id: 'tpl-200',
    name: 'Computer Systems (Coding Project Template)',
    version: 2,
    subjectCode: 'COMP30023',
    rowCount: 8,
    description:'',
    updatedAt: '2025-08-31T09:05:00.000Z',
    createdBy: 'admin',
  },
];
